# Generated by Django 3.2.8 on 2022-04-04 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indexer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.PositiveIntegerField(unique=True)),
                ('indexed_block', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.PositiveIntegerField(unique=True)),
                ('owner', models.CharField(max_length=255, verbose_name='Owners')),
                ('image', models.FileField(upload_to='images/')),
                ('chain_id', models.PositiveIntegerField()),
                ('tx', models.CharField(max_length=255)),
                ('block_number', models.PositiveBigIntegerField()),
                ('skill', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('blockchain_timestamp', models.PositiveBigIntegerField(default=None, null=True)),
                ('ipfs_uri_image', models.CharField(max_length=100, verbose_name='ifps uri image')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdraw')])),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Done')], default=1)),
                ('bridge_sender', models.CharField(max_length=255)),
                ('bridge_receiver', models.CharField(max_length=255)),
                ('l1_tx', models.CharField(max_length=255, null=True)),
                ('l2_tx', models.CharField(max_length=255, null=True)),
                ('l2_chain_id', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onbridge.token')),
            ],
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.CheckConstraint(check=models.Q(('bridge_sender', ''), _negated=True), name='non_empty_bridge_sender'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.CheckConstraint(check=models.Q(('direction__in', [1, 2])), name='Direction_choices'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.CheckConstraint(check=models.Q(('status__in', [1, 2])), name='Status_choices'),
        ),
    ]
