# Generated by Django 3.2.8 on 2021-11-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255, verbose_name='Senders')),
                ('receiver', models.CharField(max_length=255, verbose_name='Receivers')),
                ('direction', models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdraw')])),
                ('token_id', models.PositiveIntegerField()),
                ('l1_tx', models.CharField(max_length=255, verbose_name='L1 tx hashes')),
                ('l2_tx', models.CharField(max_length=255, verbose_name='L2 tx hashes')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Done')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.PositiveIntegerField(unique=True)),
                ('indexed_block', models.PositiveBigIntegerField()),
                ('oracle_block', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.PositiveIntegerField(unique=True)),
                ('owner', models.CharField(max_length=255, verbose_name='Owners')),
                ('image', models.FileField(upload_to='images/')),
                ('chain_id', models.PositiveIntegerField()),
                ('tx', models.CharField(max_length=255, verbose_name='Tx hashes')),
                ('block_number', models.PositiveBigIntegerField()),
                ('skill', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
