# Generated by Django 3.2.8 on 2022-03-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onbridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
    ]
