# Generated by Django 3.2.8 on 2022-03-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onbridge', '0002_alter_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='ipfs_uri_image',
            field=models.CharField(default='', max_length=100, verbose_name='ifps uri image'),
            preserve_default=False,
        ),
    ]
