# Generated by Django 3.2.8 on 2022-03-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onbridge', '0003_token_ipfs_uri_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='blockchain_timestamp',
            field=models.PositiveBigIntegerField(default=None, null=True),
        ),
    ]
